# Generated by Django 4.2.1 on 2023-05-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='productimg')),
                ('catagory', models.CharField(choices=[('Lap', 'Laptop'), ('mob', 'Mobile')], max_length=4)),
            ],
        ),
    ]
