# Generated by Django 4.2.1 on 2023-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('lap', 'laptops'), ('mob', 'Mobile')], max_length=4),
        ),
    ]
