# Generated by Django 4.2.1 on 2023-06-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=333)),
                ('city', models.CharField(choices=[('Lahore', 'lahore'), ('Karachi', 'karachi'), ('Islamabad', 'islamabad'), ('Faisalabad', 'faisalabad'), ('Multan', 'multan'), ('Bahawalpur', 'bahawalpur'), ('Layyah', 'layyah')], max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
